spring:
    datasource:
        username: root
        password: Gold1Silver2
        url: jdbc:mysql://localhost:3306/copperpea?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC

server:
  servlet:
    context-path: /edu
    
